### ISSUE TITLE
Eta plots don't match in signal

### ISSUE THREAD

**Issue by gordonwatts** [gordonwatts/CalRatioTrainer#124]
The jet $\eta$ plots in signal seem to be truncated around -1.5 or so:

![image](https://github.com/gordonwatts/CalRatioTrainer/assets/1778366/3a9a8f9b-6525-4f43-afb5-8c19448d865e)

In Felix's they go out to 2.5...

**Comment by alex-golub99** [comment]
the LLP eta mask is incorrect - should be two cases, |eta| < 1.4 and |eta| > 1.4, as reflected in section B.1 in the internal note.

**Comment by gordonwatts** [comment]
@alex-golub99 's fix can be found [here](https://gitlab.cern.ch/atlas-phys-exotics-llp-mscrid/fullrun2analysis/llp_nn/-/blob/main/python/process_events_alex.py#L158)
