### ISSUE TITLE
Check the jet flow cuts to make sure they are ok

### ISSUE THREAD

**Issue by gordonwatts** [gordonwatts/CalRatioTrainer#126]
Is it up stream or down stream where we are losing all the jets?

* [ ] Use a more multi-jet friendly approach to tracking clusters, mseg, etc., to enable more than one jet per event
* [ ] Check to understand what Felix does for multi-jet events
* [ ] :)

**Comment by gordonwatts** [comment]
Starting to look like the jet cuts during conversion are being rather harsh. The JZ3 file [has plenty of jets](https://gitlab.cern.ch/gwatts/divertexplorer/-/blob/master/01-jets.ipynb). So this is probably a bug in how we extract the jets. Hopefully during the `build` and not the `convert`.

**Comment by alex-golub99** [comment]
uh oh!
